name: TFPred
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.12
  - numpy=1.23.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - tqdm=4.64.0
  - scipy=1.8.1
  - pip
  - pip:
      - torch==1.13.1

